### ISSUE TITLE
Label does not seem to work

### ISSUE THREAD

**Issue by Luflosi** [linux-apfs/linux-apfs-rw#13]
The label of an APFS filesystem does not seem to show up anywhere.
The steps I tried:

1. `modprobe apfs`
2. `truncate -s 1G /tmp/test.img`
3. `losetup -f /tmp/test.img`
4. `mkapfs -L testing /dev/loop0`
5. `lsblk -f` does not show a label for loop0
6. `ls -la /dev/disk/by-label` does not show loop0
7. mounting the filesystem does not change the situation

I don't think this is a problem with mkapfs because an APFS filesystem created with macOS also does not show a label in Linux and copying /tmp/test.img to a macOS machine and mounting it does show the label.

This issue is probably very low on your TODO list. I just wanted to know if it is a known issue and if I did something wrong or if this is supposed to work.

**Comment by eafer** [comment]
As far as I know, an apfs container doesn't have a label, only the individual volumes do (my mkfs only supports creating a single volume, so that probably makes it confusing, but the label is not for the container). A volume is not its own partition and doesn't correspond to a block device, so I don't think `/dev/disk/by-label` could ever be made to work. Either way, this all sounds like userland stuff, not much can be done about it from inside the module.

**Comment by Luflosi** [comment]
Ok, that makes sense, thank you for the explanation.
I'll close this issue as there does not seem to be anything that can be changed about this module to improve the situation.
